# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2023 Ilia Sotnikov
---
i2c:
  sda: 4
  scl: 15
  scan: true

# I2C I/O expander config
pcf8574:
  - id: 'pcf8574_output_hub'
    address: 0x24
    pcf8575: false
  - id: 'pcf8574_input_hub'
    address: 0x22
xl9535:
  - id: 'xl9535_hub'
    address: 0x20

time:
  - platform: ds1307
    timezone: ${timezone}
    id: ${rtc_id}
    adress: 0x68

esphome:
  platformio_options:
    build_flags:
      # Define the preprocessor macro indicating presence of DS1307 so that
      # dependent code could be conditional
      - '-DHAS_RTC'

  on_boot:
    then:
      ds1307.read_time:
        id: ${rtc_id}
